### ISSUE TITLE
Tagged release

### ISSUE THREAD

**Issue by stevie-mayhew** [silverstripe/fluent-regional#10]
Can you tag a release for this? It makes me itchy having to rely on dev-master :smile:

**Comment by stevie-mayhew** [comment]
Is it possible to get this added to packagist as well?

**Comment by camfindlay** [comment]
Tagged release made + patch release (due to some non-code PRs merged). Will have to get time to add to packagist, for now you'll need to your a repo setting in your project composer.json.

**Comment by stevie-mayhew** [comment]
Thats what we've been doing :smile: 

Thanks @camfindlay much appreciated.
